#FC	= gfortran
#FFLAGS  = -Wall -Wtabs -fimplicit-none -ffixed-line-length-none -fPIC
FC	= ifort
#FFLAGS  = -warn -nogen-interfaces -extend-source -fPIC
FFLAGS  = -extend-source -fPIC
CFLAGS  = -Wall -Wimplicit -fPIC
RECUR   = -qrecur
CPLUS	=
MATHLIB = -L$(HOME)/$(HOSTTYPE)/lib -llapack -lblas
#SHARED_LD       = gcc -shared
#SHARED_LIB_LIBS = -L/usr/lib -lgcc -L/usr/X11R6/lib -lX11
SHARED_LD	= ld -shared
SHARED_LIB_LIBS	= -lm -lc -lX11
SHARED_EXT	= so
PGPLOT	= -L$(ALTIM)/lib -lpgplot
PMPLOT	= -L$(ALTIM)/lib -lpmplot
CPP	= /usr/bin/cpp -P $(IFLAGS) $(CPPFLAGS)
CPPFLAGS=# -traditional -E
F90	= $(FC)
NETCDF	= $(if $(NETCDFHOME),-L$(NETCDFHOME)/lib -lnetcdff -lnetcdf)
