s/RADS_VAR_CHUNK/rads_var_chunk/g
s/RADS_VARL/rads_varl/g
s/RADS_IS_OTHER/rads_is_other/g
s/RADS_IS_FLAGS/rads_is_flags/g
s/RADS_IS_SLA/rads_is_sla/g
s/RADS_IS_TIME/rads_is_time/g
s/RADS_IS_LAT/rads_is_lat/g
s/RADS_IS_LON/rads_is_lon/g
s/RADS_USE_NC_VAR/rads_use_nc_var/g
s/RADS_USE_NC_VAR/rads_use_nc_var/g
s/RADS_USE_NC_ATT/rads_use_nc_att/g
s/RADS_USE_MATH/rads_use_math/g
s/RADS_USE_BILINEAR/rads_use_bilinear/g
s/RADS_USE_CSPLINE/rads_use_cspline/g
s/RADS_NOERR/rads_noerr/g
s/RADS_ERR_NC_FILE/rads_err_nc_file/g
s/RADS_ERR_NC_PARSE/rads_err_nc_parse/g
s/RADS_ERR_NC_CLOSE/rads_err_nc_close/g
s/RADS_ERR_MEMORY/rads_err_memory/g
s/RADS_ERR_VAR/rads_err_var/g
s/RADS_ERR_SOURCE/rads_err_source/g
s/RADS_ERR_NC_VAR/rads_err_nc_var/g
s/RADS_ERR_NC_GET/rads_err_nc_get/g
s/RADS_ERR_XML_PARSE/rads_err_xml_parse/g
s/RADS_ERR_ALIAS/rads_err_alias/g
s/RADS_ERR_MAX_VAR/rads_err_max_var/g
s/RADS_ERR_MATH/rads_err_math/g
s/RADS_ERR_XML_FILE/rads_err_xml_file/g
s/RADS_ERR_CYCLE/rads_err_cycle/g
s/RADS_WARN_XML_FILE/rads_warn_xml_file/g
s/RADS_WARN_ALIAS_CIRCULAR/rads_warn_alias_circular/g
s/RADS_WARN_NC_FILE/rads_warn_nc_file/g
s/RADS_NOFIELD/rads_nofield/g
s/RADS_NOEDIT/rads_noedit/g
