FFLAGS1	=
FFLAGS2 =
FEXTSRC =
#FFLAGS2 = -Wall
#FEXTSRC = -ffixed-line-length-none
RECUR   = -qrecur
CPLUS	=
#MATHLIB = -llapack -lblas
MATHLIB = -L/opt/intel/mkl72/lib/32 -lmkl_lapack -lmkl -lguide -lpthread
SHARED_LD       = ld -shared --whole-archive
SHARED_LIB_LIBS =#
SHARED_EXT	= so
PGPLOT	= -L$(ALTIM)/lib -lpgplot -L/usr/X11R6/lib -lX11 -lpng
PMPLOT	= -L$(ALTIM)/lib -lpmplot -L/usr/X11R6/lib -lX11 -lpng
CPPFLAGS= -traditional
FC	= ifort -mp -assume byterecl -traceback -80
