#-----------------------------------------------------------------------
# Copyright (c) 2011-2024  Remko Scharroo
# See LICENSE.TXT file for copying and redistribution conditions.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#-----------------------------------------------------------------------

include ../config.mk

#-----------------------------------------------------------------------
# What to create?
#-----------------------------------------------------------------------

all:

install:	all
	$(INSTALL_DIR) $(bindir) $(datadir)/conf
	$(INSTALL_DATA) *.xml $(datadir)/conf

man:
clean:
spotless:
test:
