**INIMINI -- A crossover minimisation program
*+
* INIMINI minimises crossover height difference stored in an XXF file
* by means of an iterative Bayesian Least Squares methode. Each step
* the xover RMS over the region is stored and is used for the data
* weighting in the next step. The orbit error parameter adjustements
* are written in an XTF file
*-
**INIEDIT -- A crossover editing program
*+
* INIEDIT corrects the xover file XXF and the sea surface residual file
* XAF according to the orbit error correction parameters stored in the
* XTF file, previously generated by INIMINI
*-
* Created by Remko Scharroo
*
* Version history:
* 19 Sep 1995 - 9509.4 - Recreated from the old INIMINI version
*               by Edwin Wisse
* 20 Sep 1995 - 9509.5 - Bandmatrix version
* 21 Sep 1995 - 9509.6 - Improved editing
* 27 Sep 1995 - 9509.7 - Better smoothing of RMS grid
* 29 Sep 1995 - 9509.8 - Separate input/output grids
* 16 Oct 1995 - 9510.1 - Include xovers over "invalid" areas
*  3 Nov 1995 - 9511.2 - New version. Inisurf included
*  6 Nov 1995 - 9511.3 - New edit criteria
*  3 May 1996 - 9605.0 - Shift time tags of Geosat by 9 years.
* 30 Oct 1997 - 9710.0 - Include npar=2. Use (u-u0) as argument for
*			 parameters.
* 17 Feb 1998 - 9802.0 - Multi platform version
* 23 Mar 1998 - 9803.0 - Extra statistics output at end
*  2 Jul 1998 - 9807.0 - Make sure that itrack>32767 works
* 18 Nov 2000 - 2000.0 - Stops replaced by 'call fin'
*-----------------------------------------------------------------------
      program inimini
      implicit none

      include "init.inc"
      include "data.inc"
      include "stat.inc"
      real oresrms/0.0/,xorest
      integer onrestot/0/

      version=2000.0

* Get input and initialise some arrays

      call iniinit

* Read initial parameters

      call rdxtf

* Sort the tracks

      call sort

* Write parameters when initialised

      if (init) call wrxtf

* Start iteration

110   continue

* Initialise statistics and grid

	 call initstat
	 call initgrid

* Initialise matrix and vector

         if (inimode.gt.0) call fill_mat

* Start adding observations to matrices or edit xovers and surface
* residuals in iniedit mode.

         if (xxf.ne.' ') call xovers
	 if (xaf.ne.' ') call surface
	 if (inimode.le.0) goto 900

* Write statistics and xover rms grid

	 call wrstat
         call wrgrid

* Stop iteration when:
* - number of xovers and xover rms doesn't change significantly 
* OR
* - maximum number of iterations done.

         xorest=max(100.*abs(resrms-oresrms)/resrms,
     |		    100.*abs(nrestot-onrestot)/nrestot)
         oresrms=resrms
	 onrestot=nrestot

	 if (xorest.lt.perc
     |		.or. iter.ge.maxiter) goto 900

* Add constaints and solve the linear equations

	 iter=iter+1
         call solve_mat

* Add solution

	 call update

* Write correction parameters to track catalogue

         call wrxtf

      goto 110

* Adjust crossover file, write final statistics

900   continue

      if (inimode.ne.0) write (6,3009)
     |	ntrks,nrestot,nint(resrms0*1000),nint(resrms*1000)
      write (6,3010)

      goto 9000

* Error messages

 3009 format (/'inimini-stat:',2i8,2i4)
 3010 format (/'All is well that ends well')
 9000 continue
      end
