FFLAGS  = -Wall -Wimplicit
CFLAGS  = -Wall -Wimplicit
FEXTSRC = -ffixed-line-length-none
RECUR   = -qrecur
CPLUS	=
MATHLIB = -Wl,-framework,Accelerate
SHARED_LD       = g77 -dynamiclib -single_module
SHARED_LIB_LIBS = -L/usr/lib -lgcc -L/usr/X11R6/lib -lX11 -L/sw/lib -laquaterm -Wl,-framework,Foundation -lpng
SHARED_EXT	= dylib
PGPLOT	= -L$(ALTIM)/lib -lpgplot -Wl,-framework,Foundation
PMPLOT	= -L$(ALTIM)/lib -lpmplot -Wl,-framework,Foundation
CPP	= /usr/bin/cpp -P $(IFLAGS) $(CPPFLAGS)
CPPFLAGS=# -traditional -E
F90	= f90
NETCDF	= $(if $(NETCDFHOME),-L$(NETCDFHOME)/lib -L$(NETCDFHOME)/lib/netcdf-gfortran/lib -lnetcdff -lnetcdf)
