      IMPLICIT REAL*8 (A-Z)
      PI=4*ATAN(1D0)
      RAD=PI/180
   10 WRITE (*,*) 'ENTER CENMED, LAT, LON ->'
      READ (5,*,END=9999) CENMED,LAT,LON
      CALL GEOUTM(CENMED*RAD,LAT*RAD,LON*RAD,X,Y)
      WRITE (*,*) X,Y
      GOTO 10
 9999 END
