#!/bin/bash
#-----------------------------------------------------------------------
# $Id$
#
# Copyright (c) 2011-2014  Remko Scharroo (Altimetrics LLC)
# See LICENSE.TXT file for copying and redistribution conditions.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#-----------------------------------------------------------------------
#
# Add/overwrite numerous fields in the RADS data base
#
rads_add_grid     $* -Vdist_coast,inv_bar_mog2d_mean,gia,mss_cnescls11,basin
rads_add_grid     $* -Vgeoid_egm2008
rads_add_grid     $* -Vmss_egm2008
rads_add_grid     $* -Vmss_dtu10,topo_dtu10
rads_add_surface  $*
rads_add_tide     $* --models=stide,ptide,fes04,got48,got49,lptide,annual
rads_add_webtide  $*
rads_add_refframe $*
rads_add_sst      $* --all
rads_add_ncep     $* --dry --wet --air
rads_add_era      $* --dry --wet
